### ISSUE TITLE
Why not use Open Street Map (OSM) for Boston

### ISSUE THREAD

**Issue by hiteshPoddar** [wineslab/boston_twin#18]
This is more of a clarification question. Why did you not use OSM for Boston city and instead spend a considerable time and effort in developing this alternative? One could have just used data from OSM and overlayed the actual BS deployment in Boston on the map obtained from OSM. I couldn't find a reason in the paper as well on why OSM was not used despite Sionna documentation being a proponent of using OSM. Maybe OSM is not that accurate? Thus it impacts ray tracing performance? Looking forward to your insights on this!

**Comment by p-testolina** [comment]
Hi @hiteshPoddar,
Just to give you a bit of background, we started working with the 3D models of Boston for [this paper](https://ieeexplore.ieee.org/abstract/document/10424418). Initially, we considered the OSM 3D data, but
1. at the time there was no easy way to automate the download/extraction of the 3D models. You can obtain them using the [OverPass API](https://gis.stackexchange.com/questions/203066/building-height-in-openstreetmap), but if I remember correctly you would get a GeoJSON, which requires some parsing to convert to PLY/OBJ, as required by Sionna.
2. many of the buildings were missing the "height" field (see this: https://gmd.copernicus.org/preprints/gmd-2021-428/gmd-2021-428.pdf and [this](https://gis.stackexchange.com/questions/411124/osmbuildings-org-has-lots-of-3d-buildings-but-the-osm-source-data-doesnt-how-c)). If missing, the height, as seen for instance [here](https://osmbuildings.org/?lat=52.51938&lon=13.40571&zoom=16.0&tilt=30), is often estimated from the number of stories of the building or just assigned a default value. Since we were working on a ground-to-satellite link, having the correct height was crucial. The same applies if you're considering, for instance, UAVs and, although to a lesser extent, to ray-tracing in general.

These are the two main reasons why we resorted to an "official" data repository. The data we use for the BostonTwin is released by the [Boston Planning & Development Agency](http://www.bostonplans.org/), which is probably the most accurate and reliable source. There might be better ones if you're willing to pay for a commercial 3D model of the city.

OSM is a great resource and I'm looking forward to its future development. As of now, it's lagging a bit behind on the 3D models, but we can all contribute to it.

**Comment by p-testolina** [comment]
If you're willing to use OSM, [this repo](https://github.com/manoj-kumar-joshi/sionna_osm_scene) seems to be a good tool. I haven't tried it yet.

I'd be interested in knowing how to integrate that into the BostonTwin. What we provide in addition is some methods to convert locations to the local coordinate system, which is useful if you have your node locations in (latitude, longitude) and need to convert them to local coordinates. It would be cool to have that also for the OSM tool above.

So if you try it, please let me know.

**Comment by hiteshPoddar** [comment]
@p-testolina  thank you so much for sharing the detailed insight. [this repo](https://github.com/manoj-kumar-joshi/sionna_osm_scene) seems to probably solve your first issue to an extent but i doubt the second issue you state - that is of accurate building height is addressed. I am wondering in terms of building density/city layout, etc - in your experience do u observe significant discrepancy between OSM and the BPDA data you used? Personally i am curious to test out your boston twin and OSM on a common area in boston and perform comparison for a TN use case to see how much accuracy is really needed for 3D models of the city. In case the discrepancies are significant - it would be a good idea to scale what you have done for boston to other cities using their official databases as well. But if OSM suffices and there inst much discrepancy then one could directly use OSM (I say this because i don't that many of us working in the wireless domain, would want to spend a lot of time in creating a twin for every city like you have done - kudos for the great effort you have put in!)

**Comment by p-testolina** [comment]
Hi @hiteshPoddar,
The 2D OSM data is quite accurate. As I mentioned, there's the issue of missing heights when you move to 3D. I haven't checked the discrepancy yet, but it is something I'm planning for the future. Also, the height discrepancy is not necessarily an issue: in some scenarios, you might be fine using just the 2D model, or "guessed" heights. Think about a device-to-device comms scenario: if the nodes have a similar height that is lower than the buildings, you don't really care if it's a 20 or 30-meter-tall building. It's going to block your LoS anyway. If you instead have different TX/RX heights, or the nodes move in the 3D space, e.g., UAVs and NTNs, then you probably want to have an accurate height.

I totally agree that OSM would be a better choice to avoid having a "custom twin" and the corresponding code for each city - that's a lot of work and definitely not scalable. Hopefully, the [citySchema](https://www.cityschema.org/home/index.htm) that the data of the BostonTwin uses will be adopted by other cities, making our life easier :)
With the BostonTwin I was mainly trying to give a "benchmark" scenario to play with, where you have both accurate 3D models and antenna placement.

**Comment by p-testolina** [comment]
But let me know if you have any ideas, I'm always interested in hearing them and possibly collaborating!

**Comment by hiteshPoddar** [comment]
Hi Paolo,

Have to come across https://daylightmap.org/ ? As per my understanding
meta, microsoft and some others have been working on fixing the building
height issue in OSM and releasing it under the daylight map distribution. I
found a talk on youtube related to this:
https://www.youtube.com/watch?v=TqoFd-D0TgM. Do you happen to know if they
have released this for public usage?



On Wed, Sep 4, 2024 at 7:31 PM Paolo Testolina ***@***.***>
wrote:

> Closed #18
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_wineslab_boston-5Ftwin_issues_18&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=Ukb99gbWX0LrV6JsZSPW3A&m=wSvJnCtHqKtvbDQQMPTi_Wo2bmlIrqTBXxUzHur2KWQziF9NMkORuwrRYBV-IZfY&s=FHeZuXjMIjICQ5Y2NrOP_VZCEB9TjaWnw9ATHw4WVJM&e=>
> as completed.
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_wineslab_boston-5Ftwin_issues_18-23event-2D14139038591&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=Ukb99gbWX0LrV6JsZSPW3A&m=wSvJnCtHqKtvbDQQMPTi_Wo2bmlIrqTBXxUzHur2KWQziF9NMkORuwrRYBV-IZfY&s=RkQAN-C0gHfVK2TooM3xH3XCT2SKayrBmnDhpiplVrY&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AXDYWBRNTPM3IXA36VXNLMDZU6Q5JAVCNFSM6AAAAABJLN6XC6VHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJUGEZTSMBTHA2TSMI&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=Ukb99gbWX0LrV6JsZSPW3A&m=wSvJnCtHqKtvbDQQMPTi_Wo2bmlIrqTBXxUzHur2KWQziF9NMkORuwrRYBV-IZfY&s=ChLjNOv6-SXxk12v35jXweIuMdE-UienWSvbC6v4qAc&e=>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>


-- 
Thanks & Regards,
Hitesh

*Research Scholar(PhD), NYU Wireless, *
370 Jay St., 9th Fl.
Brooklyn, NY 11201
